DROP DATABASE IF EXISTS odg_db;
CREATE DATABASE odg_db;

CREATE TABLE products(
id INTEGER AUTO INCREMENT NOT NULL,
name VARCHAR(100) NOT NULL,
descript TEXT,
quantity INTEGER NOT NULL,

PRIMARY KEY(id)
)

DROP DATABASE IF EXISTS customers;
CREATE DATABASE customers;

CREATE TABLE User(
    id INTEGER AUTO INCREMENT NOT NULL,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(45) NOT NULL,
    company VARCHAR(45),
    email VARCHAR(100) NOT NULL,
    password PASSWORD(STRING) NOT NULL,

    PRIMARY KEY(id)
)



